---
- name: "Build docker images and push them to GCR"
  hosts: localhost
  gather_facts: false
  tasks:
  - name: "Get timestamp for docker tag"
    shell: "(date +%Y%m%d%H%M%S)"
    register: tag
  - name: Print tag
    debug:
      var: tag
  - name: Build frontend container image
    community.general.docker_image:
      build:
        path: /frontend-react-vite
      name: gcr.io/{{ gcp_project }}/arty-app-frontend-react:{{ tag.stdout}}
      source: build
  - name: Push frontend image to GCR
    community.general.docker_image:
      name: gcr.io/{{ gcp_project }}/arty-app-frontend-react:{{ tag.stdout}}
      repository: gcr.io/{{ gcp_project }}/arty-app-frontend-react:{{ tag.stdout}}
      push: yes
      source: local
  - name: Build api-service-tensorflow container image
    community.general.docker_image:
      build:
        path: /api-service-tf
      name: gcr.io/{{ gcp_project }}/arty-app-api-service-tf:{{ tag.stdout}}
      source: build
  - name: Build api-service-pytorch container image
    community.general.docker_image:
      build:
        path: /api-service-torch
      name: gcr.io/{{ gcp_project }}/arty-app-api-service-torch:{{ tag.stdout}}
      source: build
  - name: Push api-service-tf image to GCR
    community.general.docker_image:
      name: gcr.io/{{ gcp_project }}/arty-app-api-service-tf:{{ tag.stdout}}
      repository: gcr.io/{{ gcp_project }}/arty-app-api-service-tf:{{ tag.stdout}}
      push: yes
      source: local
  - name: Push api-service-torch image to GCR
    community.general.docker_image:
      name: gcr.io/{{ gcp_project }}/arty-app-api-service-torch:{{ tag.stdout}}
      repository: gcr.io/{{ gcp_project }}/arty-app-api-service-torch:{{ tag.stdout}}
      push: yes
      source: local
  - name: "Save docker tag"
    shell: echo {{ tag.stdout}} > ~/.docker-tag
  - name: "Remove all unused containers"
    shell: docker system prune -a